/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;
import beans.HistorialClinico;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static principal.FrPrincipal.IP;
import static principal.FrPrincipal.PUERTO;
import static principal.FrPrincipal.out;
import static principal.FrPrincipal.outObj;
import static principal.FrPrincipal.panelAltaCliente;
import static principal.FrPrincipal.panelAltaHistorial;
import static principal.FrPrincipal.panelAltaMascota;
import static principal.FrPrincipal.panelBienvenida;
import static principal.FrPrincipal.panelConsultaCita;
import static principal.FrPrincipal.panelConsultaCliente;
import static principal.FrPrincipal.panelConsultaHistorial;
import static principal.FrPrincipal.sc;
import static principal.FrPrincipal.panelConsultaMascota;
import static principal.FrPrincipal.panelDetalleCita;
import static principal.FrPrincipal.panelFactura;

/**
 *
 * @author Alex
 */
public class PanelAltaHistorial extends javax.swing.JPanel {
    
    public PanelAltaHistorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel23 = new javax.swing.JLabel();
        lblIdMascota = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaJuicioClinico = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        cbTratamiento = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        cbVeterinario = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        rbSi = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();
        btnGuardarHistorial = new javax.swing.JButton();
        btnCancelarHistorial = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel23.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ID MASCOTA:");

        lblIdMascota.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblIdMascota.setForeground(new java.awt.Color(255, 255, 255));
        lblIdMascota.setText("id mascota");

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Juicio clínico:");

        txaJuicioClinico.setBackground(new java.awt.Color(255, 255, 255));
        txaJuicioClinico.setColumns(20);
        txaJuicioClinico.setRows(5);
        jScrollPane1.setViewportView(txaJuicioClinico);

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Tratamiento:");

        cbTratamiento.setBackground(new java.awt.Color(255, 255, 255));
        cbTratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aa" }));
        cbTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTratamientoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DNI veterinario:");

        cbVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        cbVeterinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aaa" }));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pagado:");

        rbSi.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(rbSi);
        rbSi.setForeground(new java.awt.Color(255, 255, 255));
        rbSi.setText("SI");

        rbNo.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(rbNo);
        rbNo.setForeground(new java.awt.Color(255, 255, 255));
        rbNo.setSelected(true);
        rbNo.setText("NO");

        btnGuardarHistorial.setBackground(new java.awt.Color(0, 102, 102));
        btnGuardarHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarHistorial.setText("GUARDAR");
        btnGuardarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHistorialActionPerformed(evt);
            }
        });

        btnCancelarHistorial.setBackground(new java.awt.Color(0, 102, 102));
        btnCancelarHistorial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarHistorial.setText("CANCELAR");
        btnCancelarHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarHistorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSi)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbNo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardarHistorial)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarHistorial)))))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel13)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblIdMascota))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addContainerGap(123, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNo)
                    .addComponent(jLabel15)
                    .addComponent(rbSi))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarHistorial)
                    .addComponent(btnCancelarHistorial))
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(lblIdMascota))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel13)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cbTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(cbVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTratamientoActionPerformed

    private void btnGuardarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHistorialActionPerformed
        if (txaJuicioClinico.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debes escribir el juicio clínico");
        } else {

            
            try {
                sc = new Socket(IP, PUERTO);

                out = new DataOutputStream(sc.getOutputStream());
                //envía un mensaje al servidor para guardar historial
                out.writeUTF("guardarhistorial");

                outObj = new ObjectOutputStream(sc.getOutputStream());

                String pagado;
                //dependiendo del radiobutton seleccionado se enviará pagado o no
                if (rbSi.isSelected()) {
                    pagado = "Si";
                } else {
                    pagado = "No";
                }
                //recoge el idtratamiento del combobox tratamiento haciendo un substring
                String tratamiento = cbTratamiento.getSelectedItem().toString();
                String idtratamiento = tratamiento.substring(0, tratamiento.indexOf("."));
                
                //lo mismo para el id veterinario
                String veterinario = cbVeterinario.getSelectedItem().toString();
                String idveterinario = veterinario.substring(0, veterinario.indexOf("."));
                
                //se guarda todo en un objeto historial clinico
                HistorialClinico hc = new HistorialClinico(txaJuicioClinico.getText(), new Date(), pagado, Integer.parseInt(lblIdMascota.getText()), Integer.parseInt(idveterinario),Integer.parseInt(idtratamiento));
                //se manda el objeto al servidor
                outObj.writeObject(hc);
                outObj.close();
                out.close();

                JOptionPane.showMessageDialog(null, "Registrado en Historial clínico de la mascota");
                //después de guardarlo se volverá a poner todo por defecto
                
                panelVisible(panelConsultaMascota);
                FrPrincipal.menu.setVisible(true);
                txaJuicioClinico.setText("");
                cbTratamiento.setSelectedIndex(0);
                cbVeterinario.setSelectedIndex(0);
                rbNo.setSelected(true);
                panelConsultaMascota.btnBaja.setVisible(false);
                panelConsultaMascota.btnConsultaHistorial.setVisible(false);
                panelConsultaMascota.btnCrearHistorial.setVisible(false);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Hay problemas en la conexión con el servidor");
            }
            
        }
    }//GEN-LAST:event_btnGuardarHistorialActionPerformed

    private void btnCancelarHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarHistorialActionPerformed
        //visibiliza el menú, y oculta los botones
        FrPrincipal.menu.setVisible(true);
        panelConsultaMascota.btnConsultaHistorial.setVisible(false);
        panelConsultaMascota.btnCrearHistorial.setVisible(false);
        panelConsultaMascota.btnBaja.setVisible(false);
        //visibiliza elpanel consulta mascota
        panelVisible(panelConsultaMascota);
    }//GEN-LAST:event_btnCancelarHistorialActionPerformed

 //--------------- Método para hacer visible uno de los paneles ---------------
    public void panelVisible(JPanel p) {
        panelBienvenida.setVisible(false);
        panelAltaCliente.setVisible(false);
        panelAltaMascota.setVisible(false);
        panelConsultaMascota.setVisible(false);
        panelConsultaCliente.setVisible(false);
        panelConsultaCita.setVisible(false);
        panelDetalleCita.setVisible(false);
        panelConsultaHistorial.setVisible(false);
        panelAltaHistorial.setVisible(false);
        panelFactura.setVisible(false);

        p.setVisible(true);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarHistorial;
    private javax.swing.JButton btnGuardarHistorial;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cbTratamiento;
    public javax.swing.JComboBox<String> cbVeterinario;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblIdMascota;
    public javax.swing.JRadioButton rbNo;
    public javax.swing.JRadioButton rbSi;
    public javax.swing.JTextArea txaJuicioClinico;
    // End of variables declaration//GEN-END:variables
}
