/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static principal.FrPrincipal.IP;
import static principal.FrPrincipal.PUERTO;
import static principal.FrPrincipal.in;
import static principal.FrPrincipal.inObj;
import static principal.FrPrincipal.out;
import static principal.FrPrincipal.outObj;
import static principal.FrPrincipal.panelAltaCliente;
import static principal.FrPrincipal.panelAltaMascota;
import static principal.FrPrincipal.panelConsultaCita;
import static principal.FrPrincipal.panelConsultaCliente;
import static principal.FrPrincipal.panelConsultaMascota;
import static principal.FrPrincipal.panelDetalleCita;
import static principal.FrPrincipal.panelFactura;
import static principal.FrPrincipal.panelConsultaHistorial;
import static principal.FrPrincipal.panelAltaHistorial;
import static principal.FrPrincipal.panelBienvenida;
import static principal.FrPrincipal.sc;

/**
 *
 * @author Alex
 */
public class PanelFactura extends javax.swing.JPanel {

    public PanelFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel32 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtDireccionEmpresa = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtCiudadEmpresa = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtTlfEmpresa = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        calendario3 = new com.toedter.calendar.JDateChooser();
        btnFacturar = new javax.swing.JButton();
        btnFacturaFecha = new javax.swing.JButton();
        btnCancelarFactura = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));

        jLabel32.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Empresa:");

        txtEmpresa.setBackground(new java.awt.Color(0, 102, 102));
        txtEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        txtEmpresa.setToolTipText("");

        jLabel33.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Dirección:");

        txtDireccionEmpresa.setBackground(new java.awt.Color(0, 102, 102));
        txtDireccionEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        txtDireccionEmpresa.setToolTipText("");

        jLabel34.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Ciudad:");

        txtCiudadEmpresa.setBackground(new java.awt.Color(0, 102, 102));
        txtCiudadEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        txtCiudadEmpresa.setToolTipText("");

        jLabel35.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Teléfono:");

        txtTlfEmpresa.setBackground(new java.awt.Color(0, 102, 102));
        txtTlfEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        txtTlfEmpresa.setToolTipText("");

        jLabel36.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Elige el dia a facturar:");

        calendario3.setBackground(new java.awt.Color(0, 102, 102));
        calendario3.setForeground(new java.awt.Color(255, 255, 255));

        btnFacturar.setBackground(new java.awt.Color(0, 102, 102));
        btnFacturar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFacturar.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturar.setText("FACTURAR");
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        btnFacturaFecha.setBackground(new java.awt.Color(0, 102, 102));
        btnFacturaFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFacturaFecha.setForeground(new java.awt.Color(255, 255, 255));
        btnFacturaFecha.setText("FACTURAR POR FECHA");
        btnFacturaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaFechaActionPerformed(evt);
            }
        });

        btnCancelarFactura.setBackground(new java.awt.Color(0, 102, 102));
        btnCancelarFactura.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarFactura.setText("CANCELAR");
        btnCancelarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFacturaActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FACTURAR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jLabel7)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addComponent(txtDireccionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(calendario3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnFacturar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFacturaFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelarFactura))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCiudadEmpresa)
                                    .addComponent(txtTlfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDireccionEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33))
                    .addComponent(calendario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCiudadEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTlfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFacturar)
                    .addComponent(btnFacturaFecha)
                    .addComponent(btnCancelarFactura))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed

        try {
            sc = new Socket(IP, PUERTO);

            out = new DataOutputStream(sc.getOutputStream());
            in = new DataInputStream(sc.getInputStream());
            //recoge el modelo y el idcliente de la tabla
            DefaultTableModel m = (DefaultTableModel) panelConsultaCliente.tablaCliente.getModel();
            int idcliente = (Integer.parseInt((String) m.getValueAt(panelConsultaCliente.tablaCliente.getSelectedRow(), 0)));
            //envía el idcliente y los datos de la empresa
            out.writeUTF("@" + idcliente + "+" + txtEmpresa.getText() + "-" + txtDireccionEmpresa.getText() + "," + txtCiudadEmpresa.getText() + "." + txtTlfEmpresa.getText());
            //recibe un mensaje y si no está vacío entra
            String mensaje = in.readUTF();
            if (!mensaje.equals("")) {

                inObj = new ObjectInputStream(sc.getInputStream());
                //convierte el objeto recibido que es un archivo, en bytes
                byte[] b = (byte[]) inObj.readObject();
                //guarda el archivo, pudiendo seleccionar cualquier carpeta para guardarlo
                JFileChooser guardar = new JFileChooser();

                guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

                File archivo = new File(mensaje);
                guardar.setSelectedFile(new File(mensaje));
                guardar.showDialog(null, "Guardar archivo");
                archivo = guardar.getSelectedFile();

                //si termina en .pdf lo escribe y lo guarda
                if (archivo.getName().endsWith(".pdf")) {

                    FileOutputStream salida = new FileOutputStream(archivo);

                    salida.write(b);
                    salida.close();
                }
                inObj.close();
                out.close();
                in.close();
            } else {
                JOptionPane.showMessageDialog(null, "Este cliente no tiene facturas pendientes");
            }

            //pone la vista por defecto
            resetVistaFacturar();

        } catch (IOException ex) {
            Logger.getLogger(PanelFactura.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelFactura.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnFacturarActionPerformed

    private void btnFacturaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaFechaActionPerformed
        if (calendario3.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar una fecha");
        } else {
            try {
                sc = new Socket(IP, PUERTO);

                out = new DataOutputStream(sc.getOutputStream());
                in = new DataInputStream(sc.getInputStream());
                //recoge el modelo y el idcliente de la tabla
                DefaultTableModel m = (DefaultTableModel) panelConsultaCliente.tablaCliente.getModel();
                int idcliente = (Integer.parseInt((String) m.getValueAt(panelConsultaCliente.tablaCliente.getSelectedRow(), 0)));
                //envía el idcliente y los datos de la empresa
                out.writeUTF("(" + idcliente + "+" + txtEmpresa.getText() + "-" + txtDireccionEmpresa.getText() + "," + txtCiudadEmpresa.getText()
                        + "." + txtTlfEmpresa.getText());

                outObj = new ObjectOutputStream(sc.getOutputStream());
                //se le envía también la fecha por la que se quiere facturar
                outObj.writeObject(calendario3.getDate());
                //recibe un mensaje y si no está vacío entra
                String mensaje = in.readUTF();
                if (!mensaje.equals("")) {

                    inObj = new ObjectInputStream(sc.getInputStream());
                    //convierte el objeto recibido que es un archivo, en bytes
                    byte[] b = (byte[]) inObj.readObject();
                    //guarda el archivo, pudiendo seleccionar cualquier carpeta para guardarlo
                    JFileChooser guardar = new JFileChooser();

                    guardar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

                    File archivo = new File(mensaje);
                    guardar.setSelectedFile(new File(mensaje));
                    guardar.showDialog(null, "Guardar archivo");
                    archivo = guardar.getSelectedFile();
                    //si termina en .pdf lo escribe y lo guarda
                    if (archivo.getName().endsWith(".pdf")) {

                        FileOutputStream salida = new FileOutputStream(archivo);

                        salida.write(b);
                        salida.close();
                    }
                    inObj.close();
                    out.close();
                    in.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Este cliente no tiene facturas pendientes para esa fecha");
                }
                outObj.close();
                //pone la vista por defecto
                resetVistaFacturar();

            } catch (ClassNotFoundException | IOException ex) {
                JOptionPane.showMessageDialog(null, "Hay problemas en la conexión con el servidor");
            }
        }
    }//GEN-LAST:event_btnFacturaFechaActionPerformed

    private void btnCancelarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFacturaActionPerformed
        resetVistaFacturar();
    }//GEN-LAST:event_btnCancelarFacturaActionPerformed

    //--------------- Método para resetear la vista de facturar --------------------
    public void resetVistaFacturar() {
        //se pone la vista por defecto
        FrPrincipal.menu.setVisible(true);

        panelVisible(panelConsultaCliente);

        txtEmpresa.setText("");
        txtDireccionEmpresa.setText("");
        txtCiudadEmpresa.setText("");
        txtTlfEmpresa.setText("");
        panelConsultaCliente.calendario.setDate(null);
    }

//--------------- Método para hacer visible uno de los paneles ---------------
    public void panelVisible(JPanel p) {
        panelBienvenida.setVisible(false);
        panelAltaCliente.setVisible(false);
        panelAltaMascota.setVisible(false);
        panelConsultaMascota.setVisible(false);
        panelConsultaCliente.setVisible(false);
        panelConsultaCita.setVisible(false);
        panelDetalleCita.setVisible(false);
        panelConsultaHistorial.setVisible(false);
        panelAltaHistorial.setVisible(false);
        panelFactura.setVisible(false);

        p.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarFactura;
    public javax.swing.JButton btnFacturaFecha;
    public javax.swing.JButton btnFacturar;
    public com.toedter.calendar.JDateChooser calendario3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField txtCiudadEmpresa;
    public javax.swing.JTextField txtDireccionEmpresa;
    public javax.swing.JTextField txtEmpresa;
    public javax.swing.JTextField txtTlfEmpresa;
    // End of variables declaration//GEN-END:variables
}
