/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.Graphics;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static principal.FrPrincipal.IP;
import static principal.FrPrincipal.PUERTO;
import static principal.FrPrincipal.in;
import static principal.FrPrincipal.out;
import static principal.FrPrincipal.panelAltaHistorial;
import static principal.FrPrincipal.panelAltaMascota;
import static principal.FrPrincipal.panelConsultaCita;
import static principal.FrPrincipal.panelConsultaCliente;
import static principal.FrPrincipal.panelConsultaHistorial;
import static principal.FrPrincipal.panelConsultaMascota;
import static principal.FrPrincipal.panelDetalleCita;
import static principal.FrPrincipal.panelFactura;
import static principal.FrPrincipal.panelBienvenida;
import static principal.FrPrincipal.panelAltaCliente;
import static principal.FrPrincipal.sc;

/**
 *
 * @author Alex
 */
public class PanelAcceso extends javax.swing.JPanel {

    //variable para la imagen de fondo
    private Image imagen;
    //pongo la imagen de fondo del JPanel
    @Override
    public void paint(Graphics g) {
        imagen = new ImageIcon("src/recursos/gato2.png").getImage();
        g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        setOpaque(false);
        super.paint(g);
    }
    //creo una variable estática del JFrame
    private static FrPrincipal frp = new FrPrincipal();
    //PanelAltaCliente panelAltaCliente = new PanelAltaCliente();

    /**
     * Creates new form PanelAcceso
     */
    public PanelAcceso() {
        
        initComponents();
        
        //se ponen invisible los componentes para modificar la contraseña
        lblNuevaClave.setVisible(false);
        txtNuevaClave.setVisible(false);
        btnCancelarClave.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblNuevaClave = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        txtNuevaClave = new javax.swing.JPasswordField();
        btnAcceder = new javax.swing.JButton();
        btnModificarClave = new javax.swing.JButton();
        btnCancelarClave = new javax.swing.JButton();
        lblConsultaId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblId.setBackground(new java.awt.Color(0, 204, 204));
        lblId.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 51, 51));
        lblId.setText("ID:");

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 51));
        jLabel11.setText("Contraseña:");

        lblNuevaClave.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblNuevaClave.setForeground(new java.awt.Color(0, 51, 51));
        lblNuevaClave.setText("Nueva contraseña:");

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setToolTipText("");
        txtId.setName(""); // NOI18N

        txtClave.setBackground(new java.awt.Color(255, 255, 255));
        txtClave.setForeground(new java.awt.Color(0, 0, 0));

        txtNuevaClave.setBackground(new java.awt.Color(255, 255, 255));
        txtNuevaClave.setForeground(new java.awt.Color(0, 0, 0));

        btnAcceder.setBackground(new java.awt.Color(0, 51, 51));
        btnAcceder.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAcceder.setForeground(new java.awt.Color(255, 255, 255));
        btnAcceder.setText("ACCEDER");
        btnAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccederActionPerformed(evt);
            }
        });

        btnModificarClave.setBackground(new java.awt.Color(0, 51, 51));
        btnModificarClave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificarClave.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarClave.setText("MODIFICAR CONTRASEÑA");
        btnModificarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClaveActionPerformed(evt);
            }
        });

        btnCancelarClave.setBackground(new java.awt.Color(0, 51, 51));
        btnCancelarClave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancelarClave.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarClave.setText("CANCELAR");
        btnCancelarClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarClaveActionPerformed(evt);
            }
        });

        lblConsultaId.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        lblConsultaId.setForeground(new java.awt.Color(0, 51, 51));
        lblConsultaId.setText("Consulta tu ID");
        lblConsultaId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultaIdMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("INICIO DE SESIÓN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(lblNuevaClave)
                                    .addComponent(lblId))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNuevaClave, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(lblConsultaId))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnAcceder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarClave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarClave)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblId)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNuevaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNuevaClave))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificarClave)
                    .addComponent(btnCancelarClave)
                    .addComponent(btnAcceder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblConsultaId)
                .addGap(85, 85, 85))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccederActionPerformed
        //si no se dejan los campos vacíos entra
        if (txtId.getText().equals("") || txtClave.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Has dejado algún campo vacío");
            //si el ID es un número entra
        } else if (esNumero(txtId.getText())) {
            try {
                //se conecta al servidor
                sc = new Socket(IP, PUERTO);
                //inicializa los outout e input
                out = new DataOutputStream(sc.getOutputStream());
                in = new DataInputStream(sc.getInputStream());
                //le envía el ID y la clave al servidor
                out.writeUTF("*" + txtId.getText() + "-" + txtClave.getText());
                //si el boolean recibido es true entra
                if (FrPrincipal.in.readBoolean()) {
                    //hace invisible este panel
                    this.setVisible(false);
                    //hace visible el menú
                    FrPrincipal.menu.setVisible(true);
                    //hace visible el panel de bienvenida
                    panelBienvenida.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(null, "ID o contraseña incorrecta");
                    txtId.setText("");
                    txtClave.setText("");
                }
                //cierre de output e input
                out.close();
                in.close();

            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Hay problemas en la conexión con el servidor");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El ID no es un número");
            txtId.setText("");
            txtClave.setText("");
        }
    }//GEN-LAST:event_btnAccederActionPerformed

    private void btnModificarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClaveActionPerformed
        //si el botón tiene como cadena "GUARDAR CAMBIO" entra
        if (btnModificarClave.getText().equals("GUARDAR CAMBIO")) {
            //si ningún campo está vacío entra
            if (!txtId.getText().equals("") || !txtClave.getText().equals("") || !txtNuevaClave.getText().equals("")) {
                try {
                    //se conecta al servidor
                    sc = new Socket(IP, PUERTO);
                    //inicializa los outout e input
                    out = new DataOutputStream(sc.getOutputStream());
                    in = new DataInputStream(sc.getInputStream());
                    //envía ID, clave y nueva clave al servidor
                    out.writeUTF("%" + txtId.getText().toString() + "-" + txtClave.getText().toString() + "+" + txtNuevaClave.getText().toString());
                    boolean existe = in.readBoolean();
                    //si existe entra
                    if (existe) {
                        //pone los campos vacíos
                        txtId.setText(null);
                        txtClave.setText(null);
                        txtNuevaClave.setText(null);

                        JOptionPane.showMessageDialog(null, "La contraseña ha sido modificada");

                    } else {

                        txtId.setText(null);
                        txtClave.setText(null);
                        txtNuevaClave.setText(null);

                        JOptionPane.showMessageDialog(null, "El ID o la clave es incorrecta");
                    }

                    btnModificarClave.setText("MODIFICAR CLAVE");
                    lblNuevaClave.setVisible(false);
                    txtNuevaClave.setVisible(false);
                    
                    //cierre de output e input
                    out.close();
                    in.close();
                } catch (IOException ex) {
                    Logger.getLogger(FrPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No puedes dejar ningún campo vacío");
            }
        } else {
            //si el botón no tiene como texto "GUARDAR CAMBIO" entra aquí
            btnAcceder.setVisible(false);
            btnCancelarClave.setVisible(true);
            lblNuevaClave.setVisible(true);
            txtNuevaClave.setVisible(true);
            btnModificarClave.setText("GUARDAR CAMBIO");
        }
    }//GEN-LAST:event_btnModificarClaveActionPerformed

    private void btnCancelarClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarClaveActionPerformed
        //al pulsar en cancelar se vulve a poner los coponentes por deefecto como al inicio
        lblNuevaClave.setVisible(false);
        txtNuevaClave.setVisible(false);
        txtId.setText("");
        txtClave.setText("");
        txtNuevaClave.setText("");
        btnAcceder.setVisible(true);
        btnCancelarClave.setVisible(false);
        btnModificarClave.setText("MODIFICAR CLAVE");
    }//GEN-LAST:event_btnCancelarClaveActionPerformed

    private void lblConsultaIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultaIdMouseClicked
        //Guardo el DNI escrito en la alerta
        String dni = JOptionPane.showInputDialog("Introduce su DNI");
        //si es distinto de nulo entra
        if (dni != null) {

            try {
                sc = new Socket(IP, PUERTO);

                out = new DataOutputStream(sc.getOutputStream());
                in = new DataInputStream(sc.getInputStream());
                //envía el DNI al servidor
                out.writeUTF("\\" + dni);
                //recibe el ID del veterinario con ese DNI
                int id=in.readInt();
                //si es mayor que 0 existe y muestra el ID
                if(id>0){
                    JOptionPane.showMessageDialog(null, "Su ID es " + id);
                }else{
                    JOptionPane.showMessageDialog(null, "Su DNI no está registrado");
                }
                out.close();
                in.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Hay problemas en la conexión con el servidor");
            }

        }
    }//GEN-LAST:event_lblConsultaIdMouseClicked

//--------- Método para comprobar si la cadena es un número ------------
    public static boolean esNumero(String cadena) {

        boolean resultado;

        try {
            Integer.parseInt(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }

//--------------- Método para hacer visible uno de los paneles ---------------
    public void panelVisible(JPanel p) {
        panelBienvenida.setVisible(false);
        panelAltaCliente.setVisible(false);
        panelAltaMascota.setVisible(false);
        panelConsultaMascota.setVisible(false);
        panelConsultaCliente.setVisible(false);
        panelConsultaCita.setVisible(false);
        panelDetalleCita.setVisible(false);
        panelConsultaHistorial.setVisible(false);
        panelAltaHistorial.setVisible(false);
        panelFactura.setVisible(false);

        p.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceder;
    private javax.swing.JButton btnCancelarClave;
    private javax.swing.JButton btnModificarClave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lblConsultaId;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNuevaClave;
    public javax.swing.JPasswordField txtClave;
    public javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtNuevaClave;
    // End of variables declaration//GEN-END:variables
}
